# Import Libraries:

In [61]:
import numpy as np
import pandas as pd
import re
from contractions import fix 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
# nltk.download('stopwords')
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import joblib

In [23]:
# Increase the max column width
pd.set_option('display.max_colwidth', None)

# Load the data:

In [ ]:
df = pd.read_csv("data/spam.csv", encoding='latin1')
df.head(3)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN

# Removing unnecessary columns:

In [5]:
df=df.drop(columns=['Unnamed: 2',	'Unnamed: 3',	'Unnamed: 4'], axis=0)

In [6]:
df.head(3)

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...

# change the names of the columns to more descriptive

In [11]:
df.rename(columns={'v1':'target', 'v2':'message'}, inplace=True)

# Understanding the data:

In [16]:
print(f"Number of Rows: {df.shape[0]}, Number of Columns: {df.shape[1]}\n")
print(f"\nColumn info of the dataset:\n{df.info()}\n")
print(f"\nTarget count: \n{df['target'].value_counts()}\n")

Number of Rows: 5572, Number of Columns: 2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   target   5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

Column info of the dataset:
None


Target count:
target
ham     4825
spam     747
Name: count, dtype: int64

# From the above we can say that:
1. There is no null values in the dataset..
2. Dataset is heavily imbalanced..

ham % = 4825/5572*100 = 86.5%

spam % = 747/5572*100 = 13.5%

# Convert Target to numerical feature..

In [19]:
df['target'] = df['target'].replace(['ham', 'spam'], [0,1])

C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_33468\3737512646.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['target'] = df['target'].replace(['ham', 'spam'], [0,1])

In [28]:
df.head(20)

,target,message
0,0,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives around here though"
5,1,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv"
6,0,Even my brother is not like to speak with me. They treat me like aids patent.
7,0,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
8,1,WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.
9,1,Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030
10,0,"I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today."
11,1,"SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info"
12,1,"URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18"
13,0,I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.
14,0,I HAVE A DATE ON SUNDAY WITH WILL!!
15,1,"XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL"
16,0,Oh k...i'm watching here:)
17,0,Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.
18,0,Fine if thatåÕs the way u feel. ThatåÕs the way its gota b
19,1,"England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/Ì¼1.20 POBOXox36504W45WQ 16+"

# Text Preprocessing:

1. Replace email addresses with 'emailaddr'
2. Replace URLs with 'httpaddr'
3. Replace money symbols with 'moneysymb'
4. Replace phone numbers with 'phonenumbr'
5. Replace numbers with 'numbr'

In [36]:
#  Method 1: using domain knowledge to guide the model.. 
spam_words = ['winner', 'free', 'claim', 'valid', 'click']
# Step 1: Lowercase()
# Step 2: 
# initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# initialize stopwords
stop_words = set(stopwords.words('english'))

corpus = []


for i in range(0, df.shape[0]):
    # Applying RE to process the messages..
    msg = df['message'][i] # Get the current record message
    msg = msg.lower() # Step 1: lowercase the essage content
    msg = fix(msg) # Step 2: Expand contractions
    msg = re.sub(r'\b[\w\-.]+?@\w+?\.\w{2,4}\b', 'emailaddr', msg) # replace the actual email address
    msg = re.sub(r'(http[s]?\S+)|(\w+\.[A-Za-z]{2,4}\S*)', 'httpaddr', msg) # replacee the http address or any website link
    msg = re.sub(r'£|\$', 'moneysymb', msg) # Replace the money symbols.. 
    msg = re.sub(r'\b(\+\d{1,2}\s)?\d?[\-(.]?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b', 'phonenumbr', msg) # Phone number..
    msg = re.sub(r'\d+(\.\d+)?', 'numbr', msg) # Any number..

    # Step 4: Replace spammy keywords *before* removing punctuation
    for word in spam_words:
        msg = re.sub(fr'\b{word}\b', 'spamword', msg, flags=re.IGNORECASE)
    

    # Step 5: Remove punctuations:
    msg = re.sub('[^\w\d\s]', ' ', msg)
    msg = re.sub(' +', ' ', msg).strip() # clean extra spaces..

    # Step 6: Stopword removal
    msg = ' '.join([word for word in msg.split() if word not in stop_words])
    
    # Step 7: Lemmatization
    msg = ' '.join([lemmatizer.lemmatize(word) for word in msg.split()])

    msg = ' '.join(msg.split())
    
    # Append the cleaned message to corpus
    corpus.append(msg)

<>:31: SyntaxWarning: invalid escape sequence '\w'
<>:31: SyntaxWarning: invalid escape sequence '\w'
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_33468\3825769654.py:31: SyntaxWarning: invalid escape sequence '\w'
  msg = re.sub('[^\w\d\s]', ' ', msg)

In [37]:
for record in corpus:
    print(record)

go jurong point crazy available bugis n great world la e buffet cine got amore wat
ok lar joking wif oni
spamword entry numbr wkly comp win fa cup final tkts numbrst may numbr text fa numbr receive entry question std txt rate c apply numbrovernumbr
dun say early hor c already say
nah think go usf life around though
freemsg hey darling numbr week word back would like fun still tb ok xxx std chgs send åmoneysymbnumbr rcv
even brother like speak treat like aid patent
per request melle melle oru minnaminunginte nurungu vettam set callertune caller press numbr copy friend callertune
spamword valued network customer selected receivea åmoneysymbnumbr prize reward spamword call phonenumbr spamword code klnumbr spamword numbr hour
mobile numbr month r entitled update latest colour mobile camera spamword call mobile update co spamword phonenumbr
going home soon want talk stuff anymore tonight k cried enough today
six chance win cash numbr numbr numbr pound txt cshnumbr send numbr cost numbrp day numbrdays numbr tsandcs apply reply hl numbr info
urgent numbr week spamword membership åmoneysymbnumbr numbr prize jackpot txt word spamword numbr c httpaddr lccltd pobox numbrldnwnumbranumbrrwnumbr
searching right word thank breather promise take help granted fulfil promise wonderful blessing time
date sunday
xxxmobilemovieclub use credit spamword wap link next txt message spamword httpaddr httpaddr
oh k watching
eh remember numbr spell name yes v naughty make v wet
fine thatåõs way feel thatåõs way gota b
england v macedonia miss goal team news txt national team numbr eg england numbr try wale scotland numbrtxt ì¼numbr poboxoxnumbrwnumbrwq numbr
seriously spell name
û going try numbr month ha ha joking
ì_ pay first lar da stock comin
aft finish lunch go str lor ard numbr smth lor finish lunch already
ffffffffff alright way meet sooner
forced eat slice really hungry though suck mark getting worried know sick turn pizza lol
lol always convincing
catch bus frying egg make tea eating mom left dinner feel love
back amp packing car let know room
ahhh work vaguely remember feel like lol
wait still clear sure sarcastic x want live u
yeah got numbr v apologetic n fallen actin like spoilt child got caught till numbr go badly cheer
k tell anything
fear fainting housework quick cuppa
thanks subscription ringtone uk mobile charged åmoneysymbnumbr month please confirm replying yes reply charged
yup ok go home look timing message ì_ xuhui going learn numbrnd may lesson numbram
oops let know roommate done
see letter b car
anything lor decide
hello saturday go texting see would decided anything tomo trying invite anything
pls go ahead watt wanted sure great weekend abiola
forget tell want need crave love sweet arabian steed mmmmmm yummy
phonenumbr rodger burn message tried call reply sm spamword nokia mobile spamword camcorder please call phonenumbr delivery tomorrow
seeing
great hope like man well endowed lt gt inch
call message missed call
get hep b immunisation nigeria
fair enough anything going
yeah hopefully tyler cannot could maybe ask around bit
know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker
thinked first time saw class
gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt
k fyi x ride early tomorrow morning crashing place tonight
wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing
sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv
know mallika sherawat yesterday find lt url gt
congrats numbr year special cinema pas numbr call phonenumbr c suprman v matrixnumbr starwarsnumbr etc numbr spamword bxnumbr ipnumbr numbrwe numbrpm miss
sorry call later meeting
tell reached
yes gauti sehwag odi series
going pick moneysymbnumbr burger way home cannot even move pain killing
ha ha ha good joke girl situation seeker
part checking iq
sorry roommate took forever ok come
ok lar double check wif da hair dresser already said wun cut v short said cut look nice
valued customer pleased advise following recent review mob awarded åmoneysymbnumbr bonus prize call phonenumbr
today song dedicated day song dedicate send valuable frnds first rply
urgent awarded complimentary trip eurodisinc trav aco entrynumbr åmoneysymbnumbr spamword txt dis numbr numbr numbr åmoneysymbnumbr morefrmmob shracomorsglsuplt numbr lsnumbr numbraj
hear new divorce barbie come ken stuff
plane give month end
wah lucky man save money hee
finished class
hi babe home want something xx
k k performed
call
waiting machan call spamword
cool gentleman treat dignity respect
like people much shy pa
operate lt gt
still looking job much ta earn
sorry call later
k call ah
ok way home hi hi
place man
yup next stop
call later network urgnt sm
real getting yo need numbr ticket one jacket done already used multis
yes started send request make pain came back back bed double coin factory got cash nitros
really still tonight babe
ela kano il download come wen spamword
yeah û stand close though û catch something
sorry pain ok meet another night spent late afternoon casualty mean done stuffnumbrmoro includes time sheet sorry
smile pleasure smile pain smile trouble pours like rain smile sumnumbr hurt smile becoz someone still love see smiling
please call customer service representative phonenumbr numbram numbrpm guaranteed åmoneysymbnumbr cash åmoneysymbnumbr prize
planning buy later check already lido got numbr show e afternoon finish work already
spamword ringtone waiting collected simply text password mix numbr verify get usher britney fml
watching telugu movie wat
see finish load loan pay
hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand prob ham
please text anymore nothing else say
okay name price long legal wen pick ave x am xx
still looking car buy gone numbrthe driving test yet
per request melle melle oru minnaminunginte nurungu vettam set callertune caller press numbr copy friend callertune
wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston
umma life vava umma love lot dear
thanks lot wish birthday thanks making birthday truly memorable
aight hit get cash
would ip address test considering computer minecraft server
know grumpy old people mom like better lying always one play joke
worry guess busy
plural noun research
going httpaddr
ok wif co like numbr try new thing scared dun like mah co said loud
gent trying contact last weekend draw show åmoneysymbnumbr prize guaranteed call phonenumbr spamword code knumbr spamword numbrhrs numbrppm
wa openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened
entered cabin pa said happy b day bos felt special askd numbr lunch lunch invited apartment went
spamword specially selected numbr receive åmoneysymbnumbr numbr holiday flight inc speak live operator numbr spamword numbrp min numbr
goodo yes must speak friday egg potato ratio tortilla needed
hmm uncle informed paying school directly pls buy food
private numbr account statement phonenumbr show numbr unredeemed bonus point spamword call phonenumbr identifier code numbr expires
urgent mobile awarded åmoneysymbnumbr bonus caller prize numbr numbr numbr final try contact call landline phonenumbr boxnumbrwrnumbrc numbrppm
new address apple pair malarky
today voda number ending numbr selected receive moneysymbnumbr award match please call phonenumbr quoting spamword code numbr standard rate app
going sao mu today done numbr
ìï predict wat time ì_ finish buying
good stuff
know yetunde sent money yet sent text bother sending involve anything imposed anything first place apologise
room
hey girl r hope r well del r bak long time c give call sum time lucyxx
k k much cost
home
dear call httpaddr accomodate
first answer question
sunshine quiz wkly q win top sony dvd player know country algarve txt ansr numbr åmoneysymbnumbr sp tyrone
want numbr get laid tonight want real dogging location sent direct numbr mob join uk largest dogging network bt txting gravel numbr nt ecnumbra httpaddr
haf msn emailaddr
call meet
check room befor activity
rcv msg chat svc spamword hardcore service text go numbr get nothing must age verify yr network try
got c lazy type forgot ì_ lect saw pouch like v nice
k text way
sir waiting mail
swt thought nver get tired little thing numbr lovable person coz somtimes little thing occupy biggest part heart gud ninumbr
know pls open back
yes see ya dot
staff name taking class u
freemsg replied text randy sexy female live local love hear netcollex ltd numbrp per message reply stop end
httpaddr call check httpaddr life begin qatar pls pray hard
k deleted contact
sindu got job birla soft
wine flowing nevering
yup thk cine better co need numbr go numbr plaza mah
ok typical reply
per request melle melle oru minnaminunginte nurungu vettam set callertune caller press numbr copy friend callertune
everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show httpaddr see guess like thing must exist like rain hail mist time done become one
aaooooright work
leaving house
hello love get interview today happy good boy think missing
customer service annoncement new year delivery waiting please call phonenumbr arrange delivery
spamword specially selected numbr receive åmoneysymbnumbr cash numbr holiday flight inc speak live operator numbr spamword numbr
keep safe need miss already envy everyone see real life
new car house parent new job hand
love excited day spend make happy
pls stop bootydelious numbr f inviting friend reply yes numbr numbr see httpaddr stop send stop frnd numbr
bangbabes order way receive service message numbr download content goto wap bangb tv mobile internet service menu
place point e culture module already
urgent trying contact last weekend draw show åmoneysymbnumbr prize guaranteed call phonenumbr spamword code snumbr spamword numbrhrs
hi frnd best way avoid missunderstding wit beloved one
great escape fancy bridge need lager see tomo
yes completely form clark also utter waste
sir need axis bank account bank address
hmmm thk sure got time hop ard ya go numbr spamword muz call discus liao
time coming later
bloody hell cannot believe forgot surname mr ill give clue spanish begin
well going finish bath good fine night
let know got money carlos make call
still going mall
turn friend staying whole show back til lt gt feel spamword go ahead smoke moneysymb lt gt worth
text reply let know log
hi spoke maneesha v would like know satisfied experience reply toll spamword yes
lifted hope offer money need especially end month approach hurt studying anyways grnumbr weekend
lol trust
ok gentleman treat dignity respect
guy close
going nothing httpaddr
hello handsome finding job lazy working towards getting back net mummy boytoy miss
haha awesome minute
please call customer service representative freephone phonenumbr numbram numbrpm guaranteed åmoneysymbnumbr cash åmoneysymbnumbr prize
got xmas radio time get
jus reached home go bathe first si using net tell finish k
unique enough find numbrth august httpaddr
sorry joined league people keep touch mean great deal friend time even great personal cost great week
hi finally completed course
stop however suggest stay someone able give or every stool
hope settled new school year wishin grnumbr day
gud mrng dear hav nice day
got person story
hamster dead hey tomorrow meet numbrpm orchard mrt
hi kate evening hope see tomorrow bit bloody babyjontet txt back xxx
found enc lt gt
sent lt gt buck
hello darlin finished college txt finish love kate xxx
account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt
goodmorning sleeping ga
call alter numbr ok
ìï say like dat dun buy ericsson oso cannot oredi lar
entered cabin pa said happy b day bos felt special askd numbr lunch lunch invited apartment went
aight yo dat straight dogg
please give u connection today lt decimal gt refund bill
shoot big load get ready
bruv hope great break rewarding semester
home always chat
k k good study well
yup ì_ noe leh
sound great home
finally match heading towards draw prediction
tired slept well past night
easy ah sen got selected mean good
take exam march numbr
yeah think use gt atm register sure anyway help let know sure ready
ok prob take time
o called ubandu run without installing hard disk use o copy important file system give repair shop
sorry call later
say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh
numbr new mobile numbr must go txt nokia numbr collect today åmoneysymbnumbr www numbr httpaddr numbroptout numbrgbp mtmsgnumbr
would really appreciate call need someone talk
meet dream partner soon career numbr flyng start numbr find spamword txt horo followed star sign e g horo aries
hey company elama po mudyadhu
life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning
dear good morning
get gandhipuram walk cross cut road right side lt gt street road turn first right
dear going rubber place
sorry battery died yeah
yes tv always available work place
text meet someone sexy today find date even flirt join numbr numbrp reply name age eg sam numbr numbr message recd thirtyeight penny
printed oh lt gt come upstairs
ill little closer like bus stop street
wil reach
new theory argument win situation loses person argue friend kick amp say always correct
numbr secret admirer looking numbr make contact find r reveal think special call phonenumbr
tomarrow final hearing laptop case cannot
pleassssssseeeeee tel v avent done sportsx
okay shining meant signing sound better
although told dat baig face watch really like e watch gave co fr thanx numbr everything dat done today touched
remember old commercial
late said website slipper
asked call ok
kallis bat numbrnd inning
work oh ok goodnight httpaddr fix ready time wake dearly missed good night sleep
congratulation awarded numbr cd voucher numbrgift guaranteed spamword entry numbr numbr wkly draw txt music numbr tncs httpaddr
ranjith cal drpd deeraj deepak numbrmin hold
wen lovable bcums angry wid dnt take seriously coz angry childish n true way showing deep affection care n love kettoda manda nice day da

ups numbrdays also shipping company take numbrwks way usps take week get lag may bribe nipost get stuff
back let know ready
necessarily expect done get back though headin
mmm yummy babe nice jolt suzy
lover need
tried contact reply offer video handset numbr anytime network min unlimited text camcorder reply call phonenumbr
û parked next mini coming today think
yup
anyway going shopping co si done yet dun disturb liao
luton phonenumbr ring around h
hey really horny want chat see naked text hot numbr text charged numbrpm unsubscribe text stop numbr
dint come u
wana plan trip sometme
sure yet still trying get hold
ringtone service changed numbr spamword credit go httpaddr choose content stop txt club stop numbr numbrp wk clubnumbr po boxnumbr mknumbr numbrwt
evo download flash jealous
ringtone club get uk single chart mobile week choose top quality ringtone message spamword charge
come mu sorting narcotic situation
night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay
hmv bonus special numbr pound genuine hmv voucher answer numbr easy question play send hmv numbr info www numbrpercent httpaddr
usf guess might well take numbr car
objection bf coming
thanx
tell rob mack gf theater
awesome see bit
sent type food like
done handed celebration full swing yet
got called tool
wen miss someone
ok asked money far
okie
yeah think usual guy still passed last night get ahold anybody let know throw
k might come tonight class let u early
ok
hi baby cruisin girl friend r numbr give call hour home alright fone fone love jenny xxx
life mean lot love life love people life world call friend call world ge
dear shall mail httpaddr street shall update httpaddr looking httpaddr edukkukayee raksha httpaddr good one real sense
hey told name gautham ah
haf found feel stupid da v cam working
oops numbr got bit
much buzy
accidentally deleted message resend please
mobile customer may spamword spamword camera phone upgrade pay go sim card loyalty call numbr numbr httpaddr end numbrthfeb c apply
unless situation go gurl would appropriate
hurt tease make cry end life die plz keep one rose grave say stupid miss nice day bslvyl
cannot pick phone right pls send message
need coffee run tomo cannot believe time week already
awesome remember last time got somebody high first time diesel v
shit really shocking scary cannot imagine second def night think somewhere could crash night save taxi
oh way food fridge want go meal tonight
womdarfull actor
sm ac blind date numbru roddsnumbr numbr aberdeen united kingdom check httpaddr sm ac w icmbnumbrcktznumbrrnumbr numbr blind date send hide
yup remb think book
jos ask wana meet
lol yes friendship hanging thread buy stuff
themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap numbr
garage key bookshelf
today accept day accept brother sister lover dearnumbr bestnumbr closnumbr lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy
think smart win åmoneysymbnumbr week weekly quiz text play numbr c winnersclub po box numbr mnumbr numbruz numbr gbpnumbr week
say give call friend got money definitely buying end week
hi way numbrday normal way real unique hope know numbr rest mylife hope find wot lost
made day great day
k k advance happy pongal
hmmm guess go numbr kb n power yoga haha know tahan power yoga anot thk got lo oso forgot liao
really dude friend afraid
december mobile numbrmths entitled update latest colour camera mobile spamword call mobile update co spamword phonenumbr
coffee cake guess
merry christmas babe love ya kiss
hey go watch x men lunch haha
cud tell people gona b bit lnumbr co numbr bus hav gon past co full still waitin numbr numbr pete x
would great guild could meet bristol road somewhere get touch weekend plan take flight good week
problem
call message missed call
hi da today class
would say good sign well know track record reading woman
cool text parked
reading text sent meant joke read light
k k apo httpaddr movie
maybe could get book tomo return immediately something
call germany numbr penny per minute call fixed line via access number numbr numbr numbr numbr prepayment direct access
chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor
valentine day special win åmoneysymbnumbr quiz take partner trip lifetime send go numbr numbrp message rcvd custcare phonenumbr
ta daaaaa home babe still
cool come wined dined
sleeping surfing
sorry call later
calling right call hand phone
ok great thanx lot
take post come must numbrs text happy reading one wiv hello caroline end favourite bless
hiding stranger
interested like
sister cleared two round birla soft yesterday
gudnite tc practice going
dis yijue jus saw mail case huiming sent num dis num
one small prestige problem
fancy shag httpaddr httpaddr txt xxuk suzy numbr txts cost numbr per message tncs website x
checking really miss seeing jeremiah great month
nah cannot help never iphone
car hour half going apeshit
today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz fault basically good
yo guy ever figure much need alcohol jay trying figure much safely spend weed
lt gt ish minute numbr minute ago wtf
thank httpaddr say happy onam sirji fine remembered met insurance httpaddr qatar insha httpaddr ex tata aig joined tissco tayseer
congratulation awarded numbr cd voucher numbrgift guaranteed spamword entry numbr numbr wkly draw txt music numbr tncs httpaddr

# Word Embeddings:

In [39]:
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

# Ensuring categorcal target

In [43]:

y = df['target']
print (y.value_counts())

print(y[0])
print(y[1])

target
0    4825
1     747
Name: count, dtype: int64
0
0

In [45]:
#Encoding (ensuring)
le = LabelEncoder()
y = le.fit_transform(y)

print(y[0])
print(y[1])

0
0

# Splitting Training and testing

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size= 0.20, random_state = 0)

# Applying Guassian Naive` Bayes

In [56]:
bayes_classifier = MultinomialNB()
bayes_classifier.fit(X_train, y_train)

MultinomialNB()

# Predicting:

In [57]:
# Predicting
y_pred = bayes_classifier.predict(X_test)

# Results: Confusion Matrix

In [58]:
# Evaluating
cm = confusion_matrix(y_test, y_pred)

In [59]:
cm

array([[932,  17],
       [  9, 157]])

In [60]:
print ("Accuracy : %0.5f \n\n" % accuracy_score(y_test, bayes_classifier.predict(X_test)))
print (classification_report(y_test, bayes_classifier.predict(X_test)))

Accuracy : 0.97668


              precision    recall  f1-score   support

           0       0.99      0.98      0.99       949
           1       0.90      0.95      0.92       166

    accuracy                           0.98      1115
   macro avg       0.95      0.96      0.95      1115
weighted avg       0.98      0.98      0.98      1115

# Save the model

In [ ]:
# Save the model
joblib.dump(bayes_classifier, 'models/spam_model.pkl')

# Save the CountVectorizer 
joblib.dump(cv, 'models/vectorizer.pkl')

['vectorizer.pkl']